### ISSUE TITLE
You cannot depend simply on python-prctl

### ISSUE THREAD

**Issue by mitar** [uncharted-distil/distil-primitives#31]
It is breaking building the image: https://gitlab.com/datadrivendiscovery/images/-/jobs/231846015

It requires system packages. See [how you should define your primitives which require it](https://gitlab.com/datadrivendiscovery/common-primitives/blob/master/common_primitives/audio_reader.py#L56-80).

I will be disabling your primitives in primitives repo for now.

**Comment by cdbethune** [comment]
Fixed in latest: https://github.com/uncharted-distil/distil-primitives/blob/c8cfe98e4e1be9be4940c222a6446c76382c069a/distil/primitives/audio_transfer.py#L73-L82

**Comment by mitar** [comment]
I do not think it is correct. The order of dependencies matters. Currently, `setup.py` of your package would run first. And you still have a dependency on [python-prctl there](https://github.com/uncharted-distil/distil-primitives/blob/master/setup.py#L35). Remove it from `python-prctl`, put dependency on `python-prctl` into `installation` section, and before that put system packages. See how it is done in common primitives. Read the comment. :-)

You can try installing your primitive from primitive annotation manually inside a clean base image using [this script](https://gitlab.com/datadrivendiscovery/images/blob/master/primitives/install-primitives.py).

**Comment by cdbethune** [comment]
Updated as a recommended and CI is now passing.
